#!/bin/bash
FILE_PATH="$1"
ACCESS_TOKEN="$2"
FILE_NAME=$(basename "$FILE_PATH")
content=$(cat ${FILE_NAME} | base64 --wrap=0)
payload='{
               "message":"Upload this file to Git",
               "committer":{"name":"Mehmet", "email":"mmeram@gmail.com"},
               "content":"'
payload+=${content}
payload+='"}'
echo ${payload}
curl -L -X PUT \
     -H "Accept: application/vnd.github+json" \
     -H "Authorization: Bearer ${ACCESS_TOKEN}" \
     -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/MMeram/JsonJavaTest/contents/exports/${FILE_NAME} \
               -d "${payload}"

